[project]
name = "dros_host"
version = "0.1.0"
requires-python = "~=3.13.0"
dependencies = [
    "python-socketio>=5",
    "werkzeug>=3",
    "opencv-python",
    "pyaudio",
    "pydantic",
    "pydantic-ai",
    "pillow",
    "cbor2",
    "pocket-tts",
    "lark",
    "torch",
    "torchvision",
    "accelerate",
    "librosa",
    "scipy",
    "pywhispercpp",
    "transformers",
    "matplotlib",
    "PyQt6",
    "ultralytics",
    "tf-keras",
    "dros",
]

[project.optional-dependencies]
dev = [
    "pytest>=8",
    "python-socketio[client]>=5",
    "ruff",
    "pyright"
]

[project.scripts]
master = "dros_host.master:main"
sender = "dros_host.sender:main"

[build-system]
requires = ["setuptools>=75", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM"]
ignore = ["E501"]

[tool.pyright]
typeCheckingMode = "standard"

[tool.uv.sources]
dros = { git = "ssh://git@github.com/der/dros" }
